using BuildTruckIncidentService.Incidents.Domain.Aggregates;
using BuildTruckIncidentService.Incidents.Domain.ValueObjects;
using BuildTruckIncidentService.Shared.Infrastructure.Persistence.EFC.Configuration;

namespace BuildTruckIncidentService.Shared.Infrastructure.Persistence.EFC.Seeding;

public static class DatabaseSeeder
{
    public static async Task SeedAsync(IncidentServiceDbContext context)
    {
        if (context.Incidents.Any()) return;

        var seedIncidents = new[]
        {
            new Incident { ProjectId = 1, Title = "Accidente menor en área de excavación", Description = "Obrero se torció el tobillo durante trabajos", IncidentType = "Accident", Severity = IncidentSeverity.Low, Status = IncidentStatus.Reportado, Location = "Zona de cimentación", ReportedBy = "5", AssignedTo = "4", OccurredAt = DateTime.UtcNow.AddHours(-2), ResolvedAt = null, Image = null, Notes = "Se proporcionó atención médica", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 1, Title = "Derrame de aceite de maquinaria", Description = "Derrrame de 10 litros de aceite hidráulico", IncidentType = "Environmental", Severity = IncidentSeverity.Medio, Status = IncidentStatus.InProgress, Location = "Área de maquinaria", ReportedBy = "5", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-5), ResolvedAt = null, Image = null, Notes = "Se contaminaron 5 m2 de suelo", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 1, Title = "Falta de equipo de protección", Description = "Trabajador sin casco en zona de trabajo", IncidentType = "NearMiss", Severity = IncidentSeverity.Low, Status = IncidentStatus.Resolved, Location = "Andamiaje", ReportedBy = "4", AssignedTo = "5", OccurredAt = DateTime.UtcNow.AddDays(-1), ResolvedAt = DateTime.UtcNow.AddHours(-1), Image = null, Notes = "Se realizó capacitación al trabajador", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 1, Title = "Caída desde altura", Description = "Obrero cayó 2 metros desde andamio", IncidentType = "Accident", Severity = IncidentSeverity.High, Status = IncidentStatus.Reportado, Location = "Andamiaje nivel 2", ReportedBy = "4", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-3), ResolvedAt = null, Image = null, Notes = "Lesiones en brazo izquierdo, traslado a hospital", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 1, Title = "Incendio menor en almacén", Description = "Pequeño incendio en almacén de materiales", IncidentType = "Fire", Severity = IncidentSeverity.High, Status = IncidentStatus.Resolved, Location = "Almacén", ReportedBy = "5", AssignedTo = "4", OccurredAt = DateTime.UtcNow.AddDays(-2), ResolvedAt = DateTime.UtcNow.AddDays(-2), Image = null, Notes = "Fue controlado rápidamente", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 2, Title = "Fuga de agua en tubería", Description = "Fuga en tubería de agua potable", IncidentType = "Environmental", Severity = IncidentSeverity.Low, Status = IncidentStatus.InProgress, Location = "Sótano", ReportedBy = "4", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-4), ResolvedAt = null, Image = null, Notes = "Se está buscando la causa raíz", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 2, Title = "Ruido excesivo de maquinaria", Description = "Excavadora generando ruido superior a 90dB", IncidentType = "Environmental", Severity = IncidentSeverity.Low, Status = IncidentStatus.Reportado, Location = "Zona de excavación", ReportedBy = "5", AssignedTo = "4", OccurredAt = DateTime.UtcNow.AddHours(-1), ResolvedAt = null, Image = null, Notes = "Afecta a zonas residenciales cercanas", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 2, Title = "Golpe con objeto pesado", Description = "Trabajador golpeado por tubo de acero", IncidentType = "Accident", Severity = IncidentSeverity.Medio, Status = IncidentStatus.InProgress, Location = "Área de armado", ReportedBy = "4", AssignedTo = "5", OccurredAt = DateTime.UtcNow.AddHours(-6), ResolvedAt = null, Image = null, Notes = "Herida en cabeza, requiere puntos", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 2, Title = "Falta de orden en área de trabajo", Description = "Desorden y materiales en zona de circulación", IncidentType = "NearMiss", Severity = IncidentSeverity.Low, Status = IncidentStatus.Resolved, Location = "Acceso principal", ReportedBy = "5", AssignedTo = "4", OccurredAt = DateTime.UtcNow.AddDays(-1), ResolvedAt = DateTime.UtcNow, Image = null, Notes = "Se limpió el área", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 3, Title = "Electrocución por cable expuesto", Description = "Cable eléctrico dañado y expuesto", IncidentType = "Accident", Severity = IncidentSeverity.High, Status = IncidentStatus.Reportado, Location = "Zona de soldadura", ReportedBy = "4", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-7), ResolvedAt = null, Image = null, Notes = "Cable aislado inmediatamente", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 3, Title = "Intoxicación por vapores", Description = "Vapores tóxicos de pintura", IncidentType = "Accident", Severity = IncidentSeverity.Medio, Status = IncidentStatus.InProgress, Location = "Área de pintura", ReportedBy = "5", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-8), ResolvedAt = null, Image = null, Notes = "Se mejorió la ventilación", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 4, Title = "Colisión de vehículos en sitio", Description = "Volquete colisionó con cargador frontal", IncidentType = "Accident", Severity = IncidentSeverity.Medio, Status = IncidentStatus.Resolved, Location = "Zona de circulación", ReportedBy = "4", AssignedTo = "5", OccurredAt = DateTime.UtcNow.AddDays(-3), ResolvedAt = DateTime.UtcNow.AddDays(-2), Image = null, Notes = "Sin lesionados, daños menores", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 4, Title = "Defecto en estructura", Description = "Grieta en muro de contención", IncidentType = "StructuralDefect", Severity = IncidentSeverity.Low, Status = IncidentStatus.InProgress, Location = "Muro sur", ReportedBy = "5", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-10), ResolvedAt = null, Image = null, Notes = "Se requiere análisis estructural", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 5, Title = "Caída de objeto desde altura", Description = "Herramienta cayó desde andamio", IncidentType = "Accident", Severity = IncidentSeverity.Low, Status = IncidentStatus.Resolved, Location = "Andamiaje nivel 3", ReportedBy = "4", AssignedTo = "5", OccurredAt = DateTime.UtcNow.AddDays(-4), ResolvedAt = DateTime.UtcNow.AddDays(-3), Image = null, Notes = "Sin lesionados", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
            new Incident { ProjectId = 5, Title = "Alergia a material de construcción", Description = "Trabajador con reacción alérgica a polvo de cimento", IncidentType = "HealthHazard", Severity = IncidentSeverity.Low, Status = IncidentStatus.Reportado, Location = "Área de mezcla", ReportedBy = "5", AssignedTo = null, OccurredAt = DateTime.UtcNow.AddHours(-9), ResolvedAt = null, Image = null, Notes = "Se proporcionó mascarilla especial", UpdatedAt = DateTime.UtcNow, RegisterDate = DateTime.UtcNow },
        };

        context.Incidents.AddRange(seedIncidents);
        await context.SaveChangesAsync();
        Console.WriteLine("✅ INCIDENT SEED DATA CREATED - 16 incidents");
    }
}
